### ISSUE TITLE
Need USB access in company provided LAPTOP/MRINAL DEBNATH

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-USBALLOW#2]
am at durrah site since January 21 for commissioning work .

Lot of documentation has to submit to client related to Boiler and for which need pen drive access for print out.

But company provided LAPTOP is not allowing to work on USB.

Kindly remove the USB locking access from LAPTOP for smooth documentation work/print out work. 

I AM FACING DIFFICULTIES TO TAKE MY DOCUMENT IN PEN DRIVE.

Regards

Mrinal Debnath
EMP CODE-0737
Commissioning - Boiler
@Isgec/dc-infra-team  , Myself Praveen Kumar is working for the same.

**Comment by msrawat-isgec** [comment]
From: praveen-isgec ***@***.*** 
Sent: 18 March 2021 16:49
To: Isgec/ITIL-USBALLOW
Cc: M. S. Rawat; Team mention
Subject: [Isgec/ITIL-USBALLOW] Need USB access in company provided LAPTOP/MRINAL DEBNATH (#2)

 

am at durrah site since January 21 for commissioning work .

Lot of documentation has to submit to client related to Boiler and for which need pen drive access for print out.

But company provided LAPTOP is not allowing to work on USB.

Kindly remove the USB locking access from LAPTOP for smooth documentation work/print out work.

I AM FACING DIFFICULTIES TO TAKE MY DOCUMENT IN PEN DRIVE.

Regards

Mrinal Debnath
EMP CODE-0737
Commissioning - Boiler
@Isgec/dc-infra-team <https://github.com/orgs/Isgec/teams/dc-infra-team>  , Myself Praveen Kumar is working for the same.

**Comment by praveen-isgec** [comment]
Dear Mr. Mrinal,

 

Needful is done. Please check.

 

If not access please take restart of your system then check.

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: ***@***.***

website: www.isgec.com

Mobile:  +91 8448595785

 

From: ***@***.***
***@***.***> On Behalf Of V K Luthra
Sent: 18 March 2021 09:43
To: 'MRINAL DEBNATH' ***@***.***>; ***@***.***
Cc: 'Hariharan' ***@***.***>; ***@***.***;
'Dhirendra Singh Bisht' ***@***.***>; 'Praveen Kumar'
***@***.***>; 'Support Team63'
***@***.***>
Subject: RE: Need USB access in company provided LAPTOP/MRINAL DEBNATH

 

Ok

 

 

From: MRINAL DEBNATH ***@***.***
***@***.***> > 
Sent: 17 March 2021 17:16
To: ***@***.*** ***@***.***> 
Cc: 'Hariharan' ***@***.*** ***@***.***> >;
***@***.*** ***@***.***> ; 'Dhirendra
Singh Bisht' ***@***.***
***@***.***> >; 'Praveen Kumar'
***@***.*** ***@***.***> >; 'Support
Team63' ***@***.*** ***@***.***>
>; ***@***.*** ***@***.***> 
Subject: RE: Need USB access in company provided LAPTOP/MRINAL DEBNATH

 

'VKL' Through 'JEX'

 

I need USB full access for my laptop ( purchased through the EMI scheme).

 

Every time to take any document print out at site, I am begging another
person for using their laptop to get the document in USB from their mails.

 

Please approve.

 

Regards

 

Mrinal debnath

Commissioning Manager- Boiler



Durrah Sugar Refinery,Yanbu KSA

Mobile No:- +966554689195

Whatsapp Number +919717701403

Website:  <http://www.isgec.com/> www.isgec.com

 

From: Praveen Kumar ***@***.*** 
Sent: 17 March 2021 17:07
To: 'MRINAL DEBNATH'; 'Support Team63'
Cc: ***@***.*** ***@***.***> ; 'Hariharan';
***@***.*** ***@***.***> ; Dhirendra
Singh Bisht
Subject: RE: Need USB access in company provided LAPTOP/MRINAL DEBNATH

 

Dear Mr. Debnath,

 

We require Business Head approval for activate full usb activation in
LAPTOP.

 

Requested to you please take Business Head approval for the same.

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: ***@***.*** ***@***.***> 

website: www.isgec.com <http://www.isgec.com> 

Mobile:  +91 8448595785

 

From: ***@***.***
***@***.***>
***@***.***
***@***.***> > On Behalf Of MRINAL DEBNATH
Sent: 17 March 2021 14:47
To: 'Support Team63' ***@***.***
***@***.***> >; ***@***.***
***@***.***> 
Cc: ***@***.*** ***@***.***> ; 'Hariharan'
***@***.*** ***@***.***> >;
***@***.*** ***@***.***> 
Subject: RE: Need USB access in company provided LAPTOP/MRINAL DEBNATH

 

My  anydesk ID 142 971 944

 

Regards

 

Mrinal debnath

Commissioning Manager- Boiler



Durrah Sugar Refinery,Yanbu KSA

Mobile No:- +966554689195

Whatsapp Number +919717701403

Website:  <http://www.isgec.com/> www.isgec.com

 

From: Support Team63 ***@***.*** 
Sent: 17 March 2021 14:27
To: ***@***.*** ***@***.***> 
Cc: ***@***.*** ***@***.***> ; 'Hariharan'; 'MRINAL
DEBNATH'; ***@***.*** ***@***.***> 
Subject: RE: Need USB access in company provided LAPTOP/MRINAL DEBNATH

 

 

FYI

 

 

 

Best regards, 

Support Team - 63

Email: ***@***.*** ***@***.***> 

Website: www.isgec.com <http://www.isgec.com> 

5750/5705

 



 

From: MRINAL DEBNATH ***@***.*** 
Sent: 17 March 2021 13:13
To: ***@***.*** ***@***.***> 
Cc: ***@***.*** ***@***.***> ; 'MRINAL DEBNATH';
'Hariharan'
Subject: Need USB access in company provided LAPTOP/MRINAL DEBNATH

 

Dear Sir

 

I am at durrah site since January 21 for commissioning work .

 

Lot of documentation has to submit to client related to Boiler and for which
need pen drive access for print out.

 

But company provided LAPTOP is not allowing to work on USB.

 

Kindly remove the USB locking access from LAPTOP for smooth documentation
work/print out work. 

 

I AM FACING DIFFICULTIES TO TAKE MY DOCUMENT IN PEN DRIVE.

 

Regards

 

Mrinal Debnath

EMP CODE-0737

Commissioning - Boiler



Durrah Sugar Refinery,Yanbu KSA

Mobile No:- +966554689195

Whatsapp Number +919717701403

Website:  <http://www.isgec.com/> www.isgec.com

**Comment by praveen-isgec** [comment]
Dear Sir

 

Thank you.

 

Now I can access USB.

 

Regards

 

Mrinal Debnath.

 

From: Praveen Kumar ***@***.*** 
Sent: 18 March 2021 16:58
To: 'MRINAL DEBNATH'
Cc: 'Hariharan'; ***@***.***; 'Dhirendra Singh Bisht';
'Support Team63';
***@***.***; 'V K
Luthra'; ***@***.***
Subject: RE: Need USB access in company provided LAPTOP/MRINAL DEBNATH

 

Dear Mr. Mrinal,

 

Needful is done. Please check.

 

If not access please take restart of your system then check.

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: ***@***.***

website: www.isgec.com

Mobile:  +91 8448595785

 

From: ***@***.***
***@***.***> On Behalf Of V K Luthra
Sent: 18 March 2021 09:43
To: 'MRINAL DEBNATH' ***@***.***>; ***@***.***
Cc: 'Hariharan' ***@***.***>; ***@***.***;
'Dhirendra Singh Bisht' ***@***.***>; 'Praveen Kumar'
***@***.***>; 'Support Team63'
***@***.***>
Subject: RE: Need USB access in company provided LAPTOP/MRINAL DEBNATH

 

Ok

 

 

From: MRINAL DEBNATH ***@***.***> 
Sent: 17 March 2021 17:16
To: ***@***.***
Cc: 'Hariharan' ***@***.***>; ***@***.***;
'Dhirendra Singh Bisht' ***@***.***>; 'Praveen Kumar'
***@***.***>; 'Support Team63'
***@***.***>; ***@***.***
Subject: RE: Need USB access in company provided LAPTOP/MRINAL DEBNATH

 

'VKL' Through 'JEX'

 

I need USB full access for my laptop ( purchased through the EMI scheme).

 

Every time to take any document print out at site, I am begging another
person for using their laptop to get the document in USB from their mails.

 

Please approve.

 

Regards

 

Mrinal debnath

Commissioning Manager- Boiler



Durrah Sugar Refinery,Yanbu KSA

Mobile No:- +966554689195

Whatsapp Number +919717701403

Website:  <http://www.isgec.com/> www.isgec.com

 

From: Praveen Kumar ***@***.*** 
Sent: 17 March 2021 17:07
To: 'MRINAL DEBNATH'; 'Support Team63'
Cc: ***@***.***; 'Hariharan'; ***@***.***; Dhirendra
Singh Bisht
Subject: RE: Need USB access in company provided LAPTOP/MRINAL DEBNATH

 

Dear Mr. Debnath,

 

We require Business Head approval for activate full usb activation in
LAPTOP.

 

Requested to you please take Business Head approval for the same.

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: ***@***.***

website: www.isgec.com

Mobile:  +91 8448595785

 

From: ***@***.***
***@***.***> On Behalf Of MRINAL DEBNATH
Sent: 17 March 2021 14:47
To: 'Support Team63' ***@***.***>;
***@***.***
Cc: ***@***.***; 'Hariharan' ***@***.***>;
***@***.***
Subject: RE: Need USB access in company provided LAPTOP/MRINAL DEBNATH

 

My  anydesk ID 142 971 944

 

Regards

 

Mrinal debnath

Commissioning Manager- Boiler



Durrah Sugar Refinery,Yanbu KSA

Mobile No:- +966554689195

Whatsapp Number +919717701403

Website:  <http://www.isgec.com/> www.isgec.com

 

From: Support Team63 ***@***.*** 
Sent: 17 March 2021 14:27
To: ***@***.***
Cc: ***@***.***; 'Hariharan'; 'MRINAL DEBNATH';
***@***.***
Subject: RE: Need USB access in company provided LAPTOP/MRINAL DEBNATH

 

 

FYI

 

 

 

Best regards, 

Support Team - 63

Email: ***@***.***

Website: www.isgec.com

5750/5705

 



 

From: MRINAL DEBNATH ***@***.*** 
Sent: 17 March 2021 13:13
To: ***@***.***
Cc: ***@***.***; 'MRINAL DEBNATH'; 'Hariharan'
Subject: Need USB access in company provided LAPTOP/MRINAL DEBNATH

 

Dear Sir

 

I am at durrah site since January 21 for commissioning work .

 

Lot of documentation has to submit to client related to Boiler and for which
need pen drive access for print out.

 

But company provided LAPTOP is not allowing to work on USB.

 

Kindly remove the USB locking access from LAPTOP for smooth documentation
work/print out work. 

 

I AM FACING DIFFICULTIES TO TAKE MY DOCUMENT IN PEN DRIVE.

 

Regards

 

Mrinal Debnath

EMP CODE-0737

Commissioning - Boiler

Description: Description: Description: ***@***.***D11946.D295C1D0

Durrah Sugar Refinery,Yanbu KSA

Mobile No:- +966554689195

Whatsapp Number +919717701403

Website:  <http://www.isgec.com/> www.isgec.com

**Comment by praveen-isgec** [comment]
Needful is done...
@dhirendra-isgec   . DSB please close the call.
