### ISSUE TITLE
VKL approval for USB to Mr. Prabhakar, Munish, B S Bhati and Mr.Atul Singh EMI laptops

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-USBALLOW#3]
We received VKL approval to activate full USB access permissions for Mr. Prabhakar , Me. B s Bhati , Mr. Munish and Mr. Atul's EMI Laptop.

@Isgec/dc-infra-team  , Myself Praveen Kumar is working for the same.

**Comment by msrawat-isgec** [comment]
From: praveen-isgec ***@***.*** 
Sent: 02 April 2021 16:37
To: Isgec/ITIL-USBALLOW
Cc: M. S. Rawat; Team mention
Subject: [Isgec/ITIL-USBALLOW] VKL approval for USB to Mr. Prabhakar, Munish, B S Bhati and Mr.Atul Singh EMI laptops (#3)

 

We received VKL approval to activate full USB access permissions for Mr. Prabhakar , Me. B s Bhati , Mr. Munish and Mr. Atul's EMI Laptop.

@Isgec/dc-infra-team <https://github.com/orgs/Isgec/teams/dc-infra-team>  , Myself Praveen Kumar is working for the same.

**Comment by praveen-isgec** [comment]
Dear Mr. Prabhakar,

 

We require computer names for enable usb full access .Please share the
Computer name of laptops which are assigned to you all.

 

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: ***@***.***

website: www.isgec.com

Mobile:  +91 8448595785

 

From: Prabhakar K Sharma ***@***.***> 
Sent: 02 April 2021 15:43
To: 'vinay sharma' ***@***.***>; ***@***.***
Subject: VKL approval for USB

 

As discussed.

 

Regards,

 

Prabhakar K Sharma

Asst Manager, Boiler-Projects



A-7, Sector 63, Noida - 201 301 U.P., India

Tel. +91-120-408 5500 Ext. 5771 Direct: +91-120-4085771

Mobile: +91-84485 95665

Website: www.isgec.com <http://www.isgec.com/> 

Follow us on: Facebook <https://www.facebook.com/isgec.engg/>  | Youtube
<https://www.youtube.com/c/IsgecHeavyEngineering>  | Instagram
<https://www.instagram.com/isgec.engg/>  | LinkedIn
<https://www.linkedin.com/company/isgec-heavy-engineering-ltd/>  | Twitter
<https://twitter.com/Isgec_engg> 

 

From: ***@***.*** ***@***.***>
***@***.*** 
Sent: 02 April 2021 15:41
To: Prabhakar Sharma
Subject: Attached Image

**Comment by praveen-isgec** [comment]
[Prabhakar_BS Bhati_Munish Patiyal_Atul Singh_EMI_Laptop_USB_Allow.pdf](https://github.com/Isgec/ITIL-USBALLOW/files/6249280/Prabhakar_BS.Bhati_Munish.Patiyal_Atul.Singh_EMI_Laptop_USB_Allow.pdf)

**Comment by praveen-isgec** [comment]
Dear Mr. Prabhakar,

 

Needful is done for   "DESKTOP-9N2JHNC" - Assigned to Mr. Prabhakar.

 

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: ***@***.***

website: www.isgec.com

Mobile:  +91 8448595785

 

From: Praveen Kumar ***@***.***> 
Sent: 02 April 2021 16:52
To: 'Prabhakar K Sharma' ***@***.***>
Cc: ***@***.***'
***@***.***>; 'vinay
sharma' ***@***.***>
Subject: FW: VKL approval for USB

 

Dear Mr. Prabhakar,

 

We require computer names for enable usb full access .Please share the
Computer name of laptops which are assigned to you all.

 

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: ***@***.*** ***@***.***> 

website: www.isgec.com <http://www.isgec.com> 

Mobile:  +91 8448595785

 

From: Prabhakar K Sharma ***@***.***
***@***.***> > 
Sent: 02 April 2021 15:43
To: 'vinay sharma' ***@***.***
***@***.***> >; ***@***.***
***@***.***> 
Subject: VKL approval for USB

 

As discussed.

 

Regards,

 

Prabhakar K Sharma

Asst Manager, Boiler-Projects



A-7, Sector 63, Noida - 201 301 U.P., India

Tel. +91-120-408 5500 Ext. 5771 Direct: +91-120-4085771

Mobile: +91-84485 95665

Website: www.isgec.com <http://www.isgec.com/> 

Follow us on: Facebook <https://www.facebook.com/isgec.engg/>  | Youtube
<https://www.youtube.com/c/IsgecHeavyEngineering>  | Instagram
<https://www.instagram.com/isgec.engg/>  | LinkedIn
<https://www.linkedin.com/company/isgec-heavy-engineering-ltd/>  | Twitter
<https://twitter.com/Isgec_engg> 

 

From: ***@***.*** ***@***.***>
***@***.*** 
Sent: 02 April 2021 15:41
To: Prabhakar Sharma
Subject: Attached Image
